version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: facade/ignition
    versions:
    - 2.5.10
    - 2.5.11
    - 2.5.12
    - 2.5.13
    - 2.5.14
    - 2.5.9
    - 2.6.0
    - 2.7.0
    - 2.8.2
  - dependency-name: livewire/livewire
    versions:
    - 2.3.11
    - 2.3.14
    - 2.3.15
    - 2.3.16
    - 2.3.17
    - 2.3.18
    - 2.3.8
    - 2.4.0
    - 2.4.1
    - 2.4.2
  - dependency-name: laravel/tinker
    versions:
    - 2.6.0
  - dependency-name: nunomaduro/collision
    versions:
    - 5.3.0
  - dependency-name: laravel/framework
    versions:
    - 7.30.3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
